# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac558dc58debca49692c759a43aa4288f2bd9a786e2fcdaa4d4856230b5fafc5b78ce09bd0c008759e4791dc0a3cc58a0465edd91fe074f2b390f6ea100f1937

test:
  secret_key_base: 4522dff401985bd03118d8129e26a03dda5c9de86566dbcf8f5f20eed2dc95e8a1e9430a1c64d9131168324f83da7196947c81dc65a4cc5232dd06b1988291b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
